sudo: required
language: go
go:
- 1.6
services:
  - redis-server
script: make test

before_install:
  - openssl aes-256-cbc -K $encrypted_3eddc43c9adb_key -iv $encrypted_3eddc43c9adb_iv -in script/equinox.key.enc -out script/equinox.key -d

after_success:
  - make install_equinox
  - make release

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3888dbbd36f3739b7ee3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
